### DISCUSSION TITLE
图片居中功能

### DISCUSSION THREAD

**Discussion by leozjr** [obsidianzh/forum#66] [Ideas想法]
如题，求开发大大加入这个设置。

**Comment by Wel2018** [comment]
你可以通过“CSS代码段”的自定义样式实现该功能，例如：
``` css
.markdown-preview-view img {
  display: block;
  margin-top: 20pt;
  margin-bottom: 20pt;
  margin-left: auto;
  margin-right: auto;
  max-width: 90%;
}
```
